name: Fuzzing

on:
  schedule:
    - cron: "0 10 * * *"

jobs:
  nightly:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Rust nightly
        uses: actions-rs/toolchain@v1
        with:
          override: true
          profile: minimal
          toolchain: nightly-2021-05-28
      - name: Cache dependencies
        uses: Swatinem/rust-cache@v1

      - run: cargo install cargo-fuzz --vers "^0.10.2"
      - name: Build
        run: cargo fuzz build fuzz_test
      - name: Run fuzz test
        run: cargo fuzz run fuzz_test -- -max_total_time=14400
