name: Unit tests

on:
  push:
    branches: [master]
    paths-ignore:
      - ".husky/**"
      - "nix"
      - "sdk/**"
      - "fuzz/**"
  pull_request:
    branches: [master]
    paths-ignore:
      - ".husky/**"
      - "nix"
      - "sdk/**"
      - "fuzz/**"

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Cache Solana install
        uses: actions/cache@v2
        id: cache-solana
        with:
          path: |
            ~/.cache/solana
            ~/.local/share/solana
          key: ${{ runner.os }}-${{ hashFiles('do.sh') }}-solana

      - name: Install Solana
        if: steps.cache-solana.outputs.cache-hit != 'true'
        run: ./do.sh update
      - name: Cache Rust
        uses: Swatinem/rust-cache@v1
        with:
          key: ${{ runner.os }}-${{ hashFiles('do.sh')}}

      - name: Run unit tests
        run: ./do.sh test -- --nocapture
