name: E2E tests

on:
  push:
    branches: [master]
    paths-ignore:
      - ".husky/**"
      - "nix"
      - "fuzz/**"
      - "sdk/package.json"
  pull_request:
    branches: [master]
    paths-ignore:
      - ".husky/**"
      - "nix"
      - "fuzz/**"
      - "sdk/package.json"

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Cache SDK dependencies
        uses: actions/cache@v2
        id: cache-sdk
        with:
          path: ./sdk/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      - name: Cache Solana install
        uses: actions/cache@v2
        id: cache-solana
        with:
          path: |
            ~/.cache/solana
            ~/.local/share/solana
          key: ${{ runner.os }}-${{ hashFiles('do.sh') }}-solana

      - name: Install Solana
        if: steps.cache-solana.outputs.cache-hit != 'true'
        run: ./do.sh update
      - name: Cache Rust
        uses: Swatinem/rust-cache@v1
        with:
          key: ${{ runner.os }}-${{ hashFiles('do.sh')}}

      - name: Build
        run: ./do.sh build
      - name: Run e2e tests
        run: ./do.sh e2e-test

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: stableswap-deploy-artifact
          path: target/deploy/
