name: Release

on:
  push:
    tags:
      - "v*.*.*"

defaults:
  run:
    working-directory: sdk/

jobs:
  sdk:
    runs-on: ubuntu-latest
    name: Build and publish the SDK
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          always-auth: true
          node-version: 14.x
          registry-url: "https://npm.pkg.github.com"
      - name: Cache Node modules
        uses: actions/cache@v2
        id: cache-node-modules
        with:
          path: ./node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      - name: Install dependencies
        run: yarn install
      - name: Build SDK
        run: yarn build
      - name: Lint
        run: yarn lint
      - name: Test
        run: yarn test-unit
      - name: Publish
        run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Upload artifacts
      - name: Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
